const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const auth = require('../middlewares/auth');

router.post('/create_admin', adminController.createAdmin);
router.post('/login', adminController.adminLogin);
router.get('/get_all_customer', adminController.getAllCustomer);
router.get('/get_customer_details/:id', adminController.getCustomerDetails);
router.get('/get_customer/:id', adminController.getCustomerById);
router.post('/create_plan', adminController.createPackage);
router.get('/get_all_plan', adminController.getAllPackages);
router.get('/get_plan/:id', adminController.getPackageById);
router.put('/update_plan/:id', adminController.updatePackage);     
router.delete('/delete_plan/:id', adminController.deletePackage);
router.get('/get_all_bookings', adminController.getAllBookings);
router.get('/get_all_elite_request', adminController.getAllElitePackageRequests);
router.get('/get_all_purchase_history', adminController.getAllPurchaseHistory);
router.put("/bookings/:id/schedule", adminController.scheduleSession);
router.put("/bookings/:id/re_schedule", adminController.rescheduleSession);
router.get('/bookings/scheduled', adminController.getAllScheduledSessions);
router.get('/bookings/completed', adminController.getAllCompletedSessions);
router.get('/get_super_elite_package_request', adminController.getSuperElitePackages);
router.put('/update_super_elite_status/:id', adminController.updateSuperEliteStatus);
router.patch('/bookings/:bookingId/complete', adminController.markBookingAsCompleted);
router.get('/getAdminDashboard', adminController.getAdminDashboard);
router.get('/family-member/:id/details', adminController.getFamilyMemberFullDetails);
router.put('/update_superelite_request_price/:parentId', adminController.updateSuperEliteRequestPrice);
router.post('/deduct-session-and-update/:id', adminController.deductSessionAndUpdate);
router.post('/create_master_otp', adminController.createOrUpdateMasterOtp);
router.get('/get_master_otp', adminController.getMasterOtp);
router.put('/update-remaining-sessions/:id', adminController.updateRemainingSession);
module.exports = router;
